# Generated by Django 2.0.6 on 2018-07-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.AutoField(db_column='tno', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tname', max_length=20)),
                ('job', models.CharField(db_column='tjob', max_length=10)),
                ('intro', models.CharField(db_column='tintro', max_length=1023)),
                ('motto', models.CharField(db_column='tmotto', max_length=255)),
            ],
            options={
                'db_table': 'tb_teacher',
            },
        ),
    ]
