# Generated by Django 2.0.6 on 2018-07-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.CharField(db_column='tphoto', max_length=511, null=True),
        ),
    ]
