# Generated by Django 2.0.6 on 2018-07-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20180703_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-no',)},
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='tb_teacher',
        ),
    ]
