# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrecord',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='carrecord',
            old_name='punlish',
            new_name='punish',
        ),
    ]
