# Generated by Django 2.0.5 on 2018-05-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0002_auto_20180523_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrs.Emp'),
        ),
    ]
