# Generated by Django 2.0.7 on 2018-08-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0003_auto_20180524_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='excellent',
        ),
        migrations.AlterField(
            model_name='dept',
            name='location',
            field=models.CharField(db_column='dloc', max_length=10, verbose_name='部门所在地'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(db_column='dname', max_length=20, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='no',
            field=models.IntegerField(db_column='deptno', primary_key=True, serialize=False, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.ForeignKey(db_column='dno', on_delete=django.db.models.deletion.PROTECT, to='hrs.Dept'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='job',
            field=models.CharField(db_column='job', max_length=10),
        ),
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(db_column='ename', max_length=20),
        ),
        migrations.AlterField(
            model_name='emp',
            name='no',
            field=models.IntegerField(db_column='empno', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dept',
            table='TbDept',
        ),
        migrations.AlterModelTable(
            name='emp',
            table='TbEmp',
        ),
    ]
